<Project>
	<PropertyGroup>
		<VersionPrefix>3.6.0</VersionPrefix>
		<PackageReleaseNotes>
			- Fixed and improved validation logic for various national identification codes
            - Fixed and imporved the Smtp testing functionality.
		</PackageReleaseNotes>
		<Authors>Gianpiero Caretti</Authors>
		<Company>GP software engineering</Company>
		<Copyright>(c) 2018-26 GP software engineering</Copyright>
	</PropertyGroup>
</Project>
