<Project>
	<PropertyGroup>
		<VersionPrefix>3.5.0</VersionPrefix>
		<PackageReleaseNotes>
			- Improved QueryableExtensions.
			- updated the namespace of the HttpRequestExtension to GPSoftware.Core.Extensions.Net.
		</PackageReleaseNotes>
		<Authors>Gianpiero Caretti</Authors>
		<Company>GP software engineering</Company>
		<Copyright>(c) 2018-26 GP software engineering</Copyright>
	</PropertyGroup>
</Project>
