<Project>
	<PropertyGroup>
		<VersionPrefix>3.4.3</VersionPrefix>
		<PackageReleaseNotes>
			- Added DateOnly.Today.
			- Fixed an issue on Check.Range with default(T) values.
		</PackageReleaseNotes>
		<Authors>Gianpiero Caretti</Authors>
		<Company>GP software engineering</Company>
		<Copyright>(c) 2018-26 GP software engineering</Copyright>
	</PropertyGroup>
</Project>
